name: Deploy via FTP

on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy test website on push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v4

    - name: Check if dist folder was updated
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          dist:
            - 'dist/**'

    - name: FTP Deploy Locaweb
      if: steps.filter.outputs.dist == 'true'
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "dist"
        remoteDir: "web/"
