name: Deploy via FTP

on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy test website on push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v4

    - name: Check if commit message contains [build]
      id: check_commit_message
      run: |
        echo "Commit message: ${{ github.event.head_commit.message }}"
        if [[ "${{ github.event.head_commit.message }}" == *"[build]"* ]]; then
          echo "contains_build=true" >> $GITHUB_ENV
        else
          echo "Commit message does not contain [build]. Skipping deployment."
          echo "contains_build=false" >> $GITHUB_ENV
          exit 0
        fi

    - name: FTP Deploy Locaweb
      if: env.contains_build == 'true'
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "dist"
        remoteDir: "web/"
